apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: udagram-frontend
        image: dailebao/udagram-frontend:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m