# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-feed:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - setup_remote_docker
      - checkout
      - run:
          name: "Check docker version"
          command: "docker --version"
          
      - run:
          name: "build feed api"
          command: "docker build -t udagram-api-feed ./udagram-api-feed"

      - run:
          name: "tag image"
          command: "docker tag udagram-api-feed dailebao/udagram-api-feed:v1"

  build-user:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - setup_remote_docker
      - checkout
      - run:
          name: "Check docker version"
          command: "docker --version"
          
      - run:
          name: "build user api"
          command: "docker build -t udagram-api-user ./udagram-api-user"

      - run:
          name: "tag image"
          command: "docker tag udagram-api-user dailebao/udagram-api-user:v1"

  build-frontend:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - setup_remote_docker
      - checkout
      - run:
          name: "Check docker version"
          command: "docker --version"
          
      - run:
          name: "build udagram-frontend"
          command: "docker build -t udagram-frontend ./udagram-frontend"

      - run:
          name: "tag image"
          command: "docker tag udagram-frontend dailebao/udagram-frontend:v1"

  build-webservice:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - setup_remote_docker
      - checkout
      - run:
          name: "Check docker version"
          command: "docker --version"
          
      - run:
          name: "build udagram-reverseproxy"
          command: "docker build -t udagram-reverseproxy ./udagram-reverseproxy"

      - run:
          name: "tag image"
          command: "docker tag udagram-reverseproxy dailebao/udagram-reverseproxy:v1"

  build-push-images:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    
    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - setup_remote_docker
      - checkout
      - run:
          name: "Check docker version"
          command: "docker --version"
          
      - run:
          name: "docker login"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
      - run:
          name: "push feed"
          command: "docker push dailebao/udagram-api-feed:v1"
          
      - run:
          name: "push user"
          command: "docker push dailebao/udagram-api-user:v1"

      - run:
          name: "push frontend"
          command: "docker push dailebao/udagram-frontend:v1"      
          
      - run:
          name: "push reverseproxy"
          command: "docker push dailebao/udagram-reverseproxy:v1"            
          
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  microservice-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-feed
      - build-user
      - build-frontend
      - build-webservice
      - build-push-images:
          requires:
              - build-feed
              - build-user
              - build-frontend
              - build-webservice
      
