apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-user
  labels:
    app: backend-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api-user
  template:
    metadata:
      labels:
        app: backend-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: dailebao/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom: 
          - secretRef:
              name: cridental-secret 
          - configMapRef: 
              name: config-secret 
              
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m