apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy-deployment
  labels:
    app: udagram-reverseproxy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy-deployment
  template:
    metadata:
      labels:
        app: udagram-reverseproxy-deployment
    spec:
      containers:
      - name: udagram-reverseproxy
        image: dailebao/udagram-reverseproxy:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m